### PR TITLE
Remove unmaintained genup program

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Review by samip5 — COMMENTED** [review]
I think we should probably instead maintain it.

**Comment by jonesmz** [comment]
> I think we should probably instead maintain it.

Wouldn't we be better off having users switch to https://www.phoronix.com/news/Automated-Gentoo-Updates from the sunrise repo?

I don't have any interest in maintaining genup, i don't see the point of it, especially when there's an alternative being actively worked on.

**Comment by samip5** [comment]
Haven't seen that one before.

**Review by samip5 — APPROVED** [review]

**Comment by necrose99** [comment]
[thegreatmcpain](https://gpo.zugaina.org/Overlays/oubliette/app-portage/genup) 

https://github.com/nabbi/genup https://github.com/nabbi/oubliette-overlay

**Pull request merged**
